name: LuxeraGift Pipeline
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS  using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ls
            cd /luxera-api
            git pull origin main
            npm ci
            git status
            npm run build
            pm2 restart ecosystem.config.js --env production
            pm2 status
